export const MORE_INGREDIENTS='MORE_INGREDIENTS';
export const LESS_INGREDIENTS='LESS_INGREDIENTS';
export const INIT_INGREDIENTS='INIT_INGREDIENTS';
export const ERROR = 'ERROR';

export const START_LOADING = 'START_LOADING';

export const ORDER_COMPLETE='ORDER_COMPLETE'
export const ORDER_ERROR = 'ORDER_ERROR';
export const ORDER_PROCESS_START = 'ORDER_PROCESS_START';

export const FETCH_ORDER_START='FETCH_ORDER_START';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';

export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN='LOGIN';
export const AUTH_FAILED='AUTH_FAILED';

export const AUTH_LOGOUT='AUTH_LOGOUT'

export const AUTH_SET_RETURN_URL='AUTH_SET_RETURN_URL';
